# Generated by Django 3.0.2 on 2020-01-22 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulli', models.CharField(max_length=200)),
                ('cmimi', models.CharField(max_length=10)),
                ('foto', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Shporta',
            fields=[
                ('produkt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='e_web.Produkt')),
            ],
        ),
        migrations.CreateModel(
            name='ProdukteReja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produkt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='e_web.Produkt')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('produkt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='e_web.Produkt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
